@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYWM3ZWMzMC01N2M1LTQzZjAtOWJmMi1jZTI1YjJlNWFiYWUiLCJnaXZlbl9uYW1lIjoiSnVhbiIsImZhbWlseV9uYW1lIjoiRGVsYSBDcnV6IiwianRpIjoiODI0ZDM0ZjUtMWQ5Ni00OWIyLTljMDMtZjM3NzYxYmMxYTQ1IiwiZXhwIjoxNzQwODgwMzc3LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.fJUfcciJYnDDwObWSDnQGrHGT6KLFoHJ0JFFUQ9B59Q
GET {{host}}/dinner
Authorization: Bearer {{token}}